
# -------------------------------------------------------

# Simulation study 3 - scenario 2

# -------------------------------------------------------

#               Scenario phenology + observation spot
## Study 2
# SCENARIO 0 - changing from Bernoulli to a Poisson sampling
# SCENARIO 1 - SCENARIO 0 + X_it = psi in function of L_i
# SCENARIO 2 - SCENARIO 0 + SCENARIO 1 + p in function of L_i and V_itj
# SCENARIO 3 - SCENARIO 0 + SCENARIO 1 + SCENARIO 2 + p in function of L_i
## Study 3
# SCENARIO 1 phenology - SCENARIO 0 + SCENARIO 1 + SCENARIO 2 + SCENARIO 3 + phenology & J=10
# SCENARIO 2 phenology + spot - SCENARIO 0 + SCENARIO 1 + SCENARIO 2 + SCENARIO 3 + phenology + spot


# generating the correct true psi_it  (to compare model output with the psi generated by each scenario -- not D&S baseline)

# ---------------------------------------------------------------

rm(list = ls())
library(spOccupancy)
library(here)
library(abind)

# load simulation settings
load(here("model_output", "output_simulations", "sim-settings.RData"))

# load sampling design
load (file=here ("model_output", 
                 "output_simulations", 
                 "sampling_design_Poisson_phenology_spot.rda")
)

# Detection coefficient ---------------
# A single covariate on detection
alpha <- c(0, -0.5, -0.5) # added one coefficient for latitude

# intermediary objects
# psi
psi.true <- array(NA, dim = c(I, n.time, n.sims, n.scenarios))

# Load the data sets
load(here ("model_output", "output_simulations", "sims_D&S", "sim-data-correct.rda"))
dat.full <- dat

# load our new X.p with more secondary occasions ---------------------
load (here ("model_output", "output_simulations", "Xp_itj.rda"))

# Run simulations ---------------------------------------------------------
for (s in 1:n.sims) {
  print(paste("Currently on simulation set ", s, " out of ", n.sims, sep = ''))
  for (sc in 1:n.scenarios) {
    print(paste("Currently on scenario ", sc, " out of ", n.scenarios, sep = ''))
    set.seed(my.seeds[s])
    # index
    curr.indx <- (s - 1) * n.scenarios + sc
    dat <- dat.full[[curr.indx]]
    phi.tune <- 0.5
    
    # sim data for spOccupancy -------------------------------------------
    # L_i will replace X_it ----------------------
    L_i <- scale(dat.full[[curr.indx]]$coords[, 2])[,1]
    
    # create design matrix for covariates
    X <- array(1, dim = c(I, n.time, length(beta)))
    X[, , 2] <- L_i # set latitude here
    
    # Linear predictor for occupancy (psi)
    logit_psi <- array(0, dim = c(I, n.time))
    
    # simulate occupancy         
    for (t in 1:n.time) {
      for (i in 1:I) {
        logit_psi[i, t] <- X[i, t, ] %*% beta + 
          dat.full[[curr.indx]]$w[i,] + 
          dat.full[[curr.indx]]$eta[t,]
      }
    }
    
    # Logistic function to get occupancy probabilities
    psi <- 1 / (1 + exp(-logit_psi))
    psi.true[, , s, sc] <- psi
    
    # save
    save(psi.true, 
         file = here ("model_output", 
                      "output_simulations", 
                      "scenario_phenology_spot",
                      paste0("sim-mixed-stPGOcc-psi-true_",curr.indx,".rda"))
    )
    
    # the loop makes the array each time larger, so
    # remove files to avoid reach the upper memory bound
    # remove three output before the present output
    unlink (here ("model_output", 
                  "output_simulations", 
                  "scenario_phenology_spot",
                  paste0("sim-mixed-stPGOcc-psi-true_",curr.indx-3,".rda")),recursive=F)
    
    
  } # i (n.scenarios)
} # j (n.sims)


# end