
# list of packages to open (work with data frames, maps, plots, tables)
require(here)
require(sf)
require(ggplot2)
require(dplyr)
require(ggbreak)
require(lubridate)
require(reshape)
require(rnaturalearth)
require(rnaturalearthdata)
require(gridExtra)
require(grid)
require(units)
require(ggh4x)
require(knitr)
require(kableExtra)
require(spdep)
require("abind")
require(terra)
require(raster)
require(tidyr)

# analysis (occupancy models, processing of posterior distribution draws)
require("coda")
require(jagsUI)
require(spOccupancy)
require(spBayes)
require(MASS)  # For mvrnorm
require(MCMCvis)

